Child safety module
d-tree-org/opensrp-client-chw pull request #179
Opened 2023-10-20 10:02 UTC by devcolonel

2023-10-20 11:51 UTC, maulidkategile requested changes

2023-10-20 11:51 UTC, maulidkategile commented on opensrp-chw/src/nacp/java/org/smartregister/chw/interactor/ChildHomeVisitInteractorFlv.java
> +        ServiceWrapper serviceWrapper = serviceWrapperMap.get("Child Safety");
The referenced recurring service starts with a lowercase letter, resulting in a null serviceWrapper object

2023-10-24 07:49 UTC, maulidkategile approved these changes

2023-10-30 16:35 UTC, issyzac commented
@devcolonel please work on the conflicts so that the changes can be merged

2023-11-01 09:55 UTC, issyzac requested changes
Can you run and test and make sure the service is available

2023-11-01 09:55 UTC, issyzac commented on opensrp-chw/src/main/java/org/smartregister/chw/actionhelper/ChildHVChildSafetyActionHelper.java
> +        } else if ("no".equals(subtitleText)) {
In the json file the key is different from what you are equating it to here

2023-11-01 11:44 UTC, issyzac approved these changes
Looks good.

2023-11-01 12:27 UTC, merged